baseurl: "/"
languageCode: "en-us"
title: "Powercoders"
enableRobotsTXT: true
disableKinds:
  - taxonomy
  - taxonomyTerm

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    title: Meet the team
    url: /about/
    weight: 2
  - identifier: program
    name: Program
    title: Get involved
    url: /program/
    weight: 3
  - identifier: membership
    name: Membership
    title: Join out community
    url: /membership/
    weight: 4
  - identifier: donate
    name: Donate
    title: Help us create a better future
    url: /donate/
    weight: 5
  - identifier: press
    name: Press
    title: Press releases and our press kit
    url: /press/
    weight: 6
  - identifier: faq
    name: faq
    title: Frequently Asked Questions
    url: /faq/
    weight: 7
