baseurl: "/"
languageCode: "en-us"
title: "Powercoders"
enableRobotsTXT: true
publish_mode: editorial_workflow
disableKinds:
  - taxonomy
  - taxonomyTerm

# This menu is shown at the top of each page close to the logo.
menu:
  main:
  - identifier: students
    name: Students
    title: Information for students
    url: /students/
    weight: 1
  - identifier: companies
    name: Companies
    title: Information for companies
    url: /companies/
    weight: 2
  - identifier: volunteers
    name: Volunteers
    title: Information for volunteers
    url: /volunteers/
    weight: 3
  - identifier: about
    name: About
    title: Meet the team
    url: /about/
    weight: 5
  - identifier: press
    name: Press
    title: Press releases and our press kit
    url: /press/
    weight: 6
