backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: site/static/img
public_folder: img

collections:
  - name: pages
    label: Pages
    files:
      - file: site/content/_index.md
        label: Home Page
        name: home
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: header
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Video Id
                name: video_id
                widget: string
                required: false
          - label: Teaser Image
            name: teaser_image
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
          - label: Get Involved
            name: get_involved
            widget: object
            fields:
              - label: Content
                name: content
                widget: markdown
          - label: Program
            name: program
            widget: list
            fields:
              - label: Heading
                name: header
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Link
                name: link
                widget: string
              - label: Link Text
                name: link_text
                widget: string
              - label: Fade In Animation
                name: fade_in
                widget: select
                options: ["Left", "Right", "Up", "Down"]
          - label: Latest
            name: latest
            widget: list
            fields:
              - label: Heading
                name: header
                widget: string
              - label: Heading Icon
                name: header_icon
                widget: string
              - label: Text
                name: text
                widget: text
              - label: link
                name: link
                widget: string
              - label: Link Text
                name: link_text
                widget: string
              - label: Fade In Animation
                name: fade_in
                widget: select
                options: ["Left", "Right", "Up", "Down"]
          - label: Teaser Image 2
            name: teaser_image2
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
              - label: Text
                name: text
                widget: string
          - label: Story
            name: story
            widget: object
            fields:
              - label: Text
                name: text
                widget: markdown
                required: false
              - label: Video Id
                name: video_id
                widget: string
          - label: Partner
            name: partner
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Image
                name: image
                widget: image
              - label: link
                name: link
                widget: string
              - label: Size
                name: size
                widget: select
                default: "s12 m6"
                options:
                    - { label: "Large", value: "s12 m6" }
                    - { label: "Medium", value: "s6 m4" }
                    - { label: "Small", value: "s6 m2" }
          - label: Community Partner
            name: community_partner
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Image
                name: image
                widget: image
              - label: link
                name: link
                widget: string
              - label: Size
                name: size
                widget: select
                default: "s12 m6"
                options:
                    - { label: "Large", value: "s12 m6" }
                    - { label: "Medium", value: "s6 m4" }
                    - { label: "Small", value: "s6 m2" }
          - label: Company Member
            name: company_member
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Image
                name: image
                widget: image
              - label: link
                name: link
                widget: string
              - label: Size
                name: size
                widget: select
                default: "s12 m6"
                options:
                    - { label: "Large", value: "s12 m6" }
                    - { label: "Medium", value: "s6 m4" }
                    - { label: "Small", value: "s6 m2" }
      - file: site/content/about/_index.md
        label: About
        name: about
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Timeline
            name: timeline
            widget: list
            fields:
              - label: date
                name: date
                widget: string
              - label: Text
                name: text
                widget: string
          - label: Team
            name: team
            widget: object
            fields:
              - label: Text
                name: text
                widget: markdown
              - label: Members
                name: members
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Image
                    name: image
                    widget: image
                  - label: Description
                    name: description
                    widget: string

      - file: site/content/membership/_index.md
        label: Membership
        name: member
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Member
            name: member
            widget: object
            fields:
              - label: header
                name: header
                widget: string
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: string
              - label: Call to action
                name: call_to_action
                widget: string

      - file: site/content/donate/_index.md
        label: Donate
        name: donate
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Causes
            name: causes
            widget: list
            fields:
              - label: Text
                name: text
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: Align
                name: align
                widget: select
                options: ["left", "right"]

      - file: site/content/press/_index.md
        label: Press
        name: press
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Media
            name: media
            widget: list
            fields:
              - label: Year
                name: year
                widget: string
              - label: Entries
                name: entries
                widget: list
                fields:
                  - label: Date
                    name: date
                    widget: string
                  - label: Links
                    name: links
                    widget: list
                    fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: Link
                        name: link
                        widget: string
                      - label: Link Text
                        name: link_text
                        widget: string

      - file: site/content/faq/_index.md
        label: Faq
        name: faq
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Sections
            name: sections
            widget: list
            fields:
              - label: name
                name: name
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: string
                  - label: Text
                    name: text
                    widget: markdown

      - file: site/content/program/_index.md
        label: Program
        name: program
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Roles
            name: roles
            widget: list
            fields:
              - label: Header
                name: header
                widget: string
              - label: Text
                name: text
                widget: markdown
          - label: City Program
            name: city_program
            widget: object
            fields:
              - label: Header
                name: header
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: string
                  - label: Text
                    name: text
                    widget: markdown
                  - label: Link
                    name: link
                    widget: string
                  - label: Color
                    name: color
                    widget: string
                  - label: Fade In
                    name: fade_in
                    widget: select
                    options: ["Left", "Right", "Up", "Down"]
                  - label: Call to action
                    name: call_to_action
                    widget: string
          - label: Past Program
            name: past_program
            widget: object
            fields:
              - label: Header
                name: header
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: string
                  - label: Text
                    name: text
                    widget: string
                  - label: Link
                    name: link
                    widget: string

  - name: cities
    label: Cities
    folder: site/content/city
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
        required: false
      - label: Section Title
        name: section_title
        widget: string
      - label: Text
        name: text
        widget: markdown
      - label: Events
        name: events
        widget: list
        required: false
        fields:
          - label: Header
            name: header
            widget: string
          - label: Heading Icon
            name: header_icon
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: link
            name: link
            widget: string
            required: false
          - label: Call to action
            name: call_to_action
            widget: string
            required: false
          - label: Meetup Link (Full URL)
            name: meetup_link
            widget: string
            required: false
      - label: Apply as
        name: apply_as
        widget: list
        required: false
        fields:
          - label: Header
            name: header
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Application link
            name: application_link
            widget: string
            hint: URL people will go to in order to apply
            required: false
      - label: Team
        name: team
        widget: object
        fields:
          - label: Header
            name: header
            widget: string
          - label: Members
            name: members
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Description
                name: description
                widget: string
              - label: Email
                name: email
                widget: string
                required: false
      - label: Partner
        name: partner
        widget: list
        fields:
          - label: Name
            name: name
            widget: string
          - label: Image
            name: image
            widget: image
          - label: link
            name: link
            widget: string
          - label: Size
            name: size
            widget: select
            default: "s12 m6"
            options:
                - { label: "Large", value: "s12 m6" }
                - { label: "Medium", value: "s6 m4" }
                - { label: "Small", value: "s6 m2" }
      - label: Industry Partner
        name: industry_partner
        required: false
        widget: list
        fields:
          - label: Name
            name: name
            widget: string
          - label: Image
            name: image
            widget: image
          - label: link
            name: link
            widget: string
      - label: FAQs
        name: faqs
        required: false
        widget: list
        fields:
          - label: Header
            name: header
            widget: string
          - label: Text
            name: text
            widget: markdown

  - name: helpers
    label: Helpers
    files:
      - file: site/content/privacy-policy/_index.md
        label: Privacy Policy
        name: privacy_policy
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: Exclude from Search
            name: search_exclude
            widget: select
            default: "no"
            options: ["yes", "no"]

      - file: site/content/terms-and-conditions/_index.md
        label: Terms and Conditions
        name: terms_and_conditions
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: Exclude from Search
            name: search_exclude
            widget: select
            default: "no"
            options: ["yes", "no"]
