backend:
  name: git-gateway
  branch: redesign-2019-11

publish_mode: editorial_workflow

media_folder: site/static/img
public_folder: img

collections:
  - name: pages
    label: Pages
    files:
      - file: site/content/_index.md
        label: Home Page
        name: home
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: header
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Video Id
                name: video_id
                widget: string
                required: false
          - label: Teaser Image
            name: teaser_image
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
          - label: Get Involved
            name: get_involved
            widget: object
            fields:
              - label: Content
                name: content
                widget: markdown
          - label: Donut charts
            name: donuts
            widget: list
            fields:
              - label: Percentage
                name: Percentage
                widget: number
                valuetype: "int"
                min: 1
                max: 100
              - label: Description
                name: description
                widget: string
          - label: Program
            name: program
            widget: list
            fields:
              - label: Heading
                name: header
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Link
                name: link
                widget: string
              - label: Link Text
                name: link_text
                widget: string
              - label: Fade In Animation
                name: fade_in
                widget: select
                options: ["Left", "Right", "Up", "Down"]
          - label: Latest
            name: latest
            widget: list
            fields:
              - label: Heading
                name: header
                widget: string
              - label: Heading Icon
                name: header_icon
                widget: string
              - label: Text
                name: text
                widget: text
              - label: link
                name: link
                widget: string
              - label: Link Text
                name: link_text
                widget: string
              - label: Fade In Animation
                name: fade_in
                widget: select
                options: ["Left", "Right", "Up", "Down"]
          - label: Teaser Image 2
            name: teaser_image2
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
              - label: Text
                name: text
                widget: string
              - label: Video Id
                name: video_id
                widget: string
      - file: site/content/about/_index.md
        label: About
        name: about
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Timeline
            name: timeline
            widget: list
            fields:
              - label: date
                name: date
                widget: string
              - label: Text
                name: text
                widget: string
          - label: Team
            name: team
            widget: object
            fields:
              - label: Text
                name: text
                widget: markdown
              - label: Members
                name: members
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Image
                    name: image
                    widget: image
                  - label: Description
                    name: description
                    widget: string
      - file: site/content/alumni/_index.md
        label: Alumni
        name: alumni
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown

      - file: site/content/membership/_index.md
        label: Membership
        name: member
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Member
            name: member
            widget: object
            fields:
              - label: header
                name: header
                widget: string
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: string
              - label: Call to action
                name: call_to_action
                widget: string

      - file: site/content/donate/_index.md
        label: Donate
        name: donate
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Causes
            name: causes
            widget: list
            fields:
              - label: Text
                name: text
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: Align
                name: align
                widget: select
                options: ["left", "right"]

      - file: site/content/press/_index.md
        label: Press
        name: press
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Media
            name: media
            widget: list
            fields:
              - label: Year
                name: year
                widget: string
              - label: Entries
                name: entries
                widget: list
                fields:
                  - label: Date
                    name: date
                    widget: string
                  - label: Links
                    name: links
                    widget: list
                    fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: Link
                        name: link
                        widget: string
                      - label: Link Text
                        name: link_text
                        widget: string

      - file: site/content/faq/_index.md
        label: Faq
        name: faq
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Sections
            name: sections
            widget: list
            fields:
              - label: name
                name: name
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: string
                  - label: Text
                    name: text
                    widget: markdown

      - file: site/content/program/_index.md
        label: Program
        name: program
        fields:
          - label: Title
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Section Title
            name: section_title
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Roles
            name: roles
            widget: list
            fields:
              - label: Header
                name: header
                widget: string
              - label: Text
                name: text
                widget: markdown
          - label: City Program
            name: city_program
            widget: object
            fields:
              - label: Header
                name: header
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: string
                  - label: Text
                    name: text
                    widget: markdown
                  - label: Link
                    name: link
                    widget: string
                  - label: Color
                    name: color
                    widget: string
                  - label: Fade In
                    name: fade_in
                    widget: select
                    options: ["Left", "Right", "Up", "Down"]
                  - label: Call to action
                    name: call_to_action
                    widget: string
          - label: Past Program
            name: past_program
            widget: object
            fields:
              - label: Header
                name: header
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Header
                    name: header
                    widget: string
                  - label: Text
                    name: text
                    widget: string
                  - label: Link
                    name: link
                    widget: string

  - name: cities
    label: Cities
    folder: site/content/city
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
        required: false
      - label: Section Title
        name: section_title
        widget: string
      - label: Text
        name: text
        widget: markdown
      - label: Events
        name: events
        widget: list
        required: false
        fields:
          - label: Header
            name: header
            widget: string
          - label: Heading Icon
            name: header_icon
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: link
            name: link
            widget: string
            required: false
          - label: Call to action
            name: call_to_action
            widget: string
            required: false
          - label: Meetup Link (Full URL)
            name: meetup_link
            widget: string
            required: false
      - label: Apply as
        name: apply_as
        widget: list
        required: false
        fields:
          - label: Header
            name: header
            widget: string
          - label: Text
            name: text
            widget: markdown
          - label: Application link
            name: application_link
            widget: string
            hint: URL people will go to in order to apply
            required: false
      - label: Team
        name: team
        widget: object
        fields:
          - label: Header
            name: header
            widget: string
          - label: Members
            name: members
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Description
                name: description
                widget: string
              - label: Email
                name: email
                widget: string
                required: false
      - label: FAQs
        name: faqs
        required: false
        widget: list
        fields:
          - label: Header
            name: header
            widget: string
          - label: Text
            name: text
            widget: markdown

  - label: "Events"
    name: events
    format: json
    folder: "site/data/events"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
        hint: "1-3 words maximum"
      - label: Icon
        name: header_icon
        widget: select
        options:
          - {label: "Graduation Party", value: "fa-graduation-cap"}
          - {label: "Handshake", value: "fa-handshake"}
          - {label: "Launch Party", value: "fa-rocket"}
          - {label: "Video", value: "fa-video"}
        hint: "Choose an icon for this event"
      - label: Audience
        name: audience
        widget: select
        multiple: true
        options: ["student", "volunteer", "company"]
        hint: "The event will be shown on the home page, and the pages for all the audiences you choose here"
      - label: City
        name: city
        widget: select
        multiple: true
        options: ["lausanne", "zurich"]
        hint: "The event will be shown on the home page, and the pages for all the cities you choose here"
      - label: Text
        name: text
        widget: markdown
        hint: "1-2 sentences maximum"
      - label: link
        name: link
        widget: string
        required: false
      - label: Call to action
        name: call_to_action
        widget: string
        required: false
        hint: "The text shown on the link. E.g., 'Sign up' or 'Watch', or 'More'"
      - label: Meetup Link (Full URL)
        name: meetup_link
        widget: string
        required: false
        hint: "If you don't include a regular link you must include a Meetup link!"
      - label: Remove after...
        name: remove_after
        widget: datetime
        required: false
        default: ""
        hint: "If this is set the event will be removed from the page after this time"

  - name: partners
    label: "Partners"
    format: json
    folder: "site/data/partners"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
      - label: URL
        name: link
        widget: string
      - label: Type
        name: type
        widget: select
        options:
          - {label: "Partner", value: "partner"}
          - {label: "Community Partner", value: "community_partner"}
          - {label: "Company Member", value: "company_member"}
        hint: "Choose the type of partner"
      - label: City
        name: city
        required: false
        widget: select
        multiple: true
        options: ["lausanne", "zurich"]
        hint: "By default partners are shown on all city pages, restrict them to a particular city here"

  - name: alumni
    label: "Alumni"
    format: json
    folder: "site/data/alumni"
    create: true
    fields:
      - label: Name
        name: title
        widget: string
        hint: Must be unique across all alumni, use "Display name"
      - label: "Display Name"
        name: display_name
        widget: string
        required: false
      - label: Image
        name: image
        widget: image
      - label: Background
        name: Background
        widget: string
      - label: Quote
        name: quote
        widget: string
      - label: Story
        name: story
        widget: markdown
        required: false

  - name: helpers
    label: Helpers
    files:
      - file: site/content/privacy-policy/_index.md
        label: Privacy Policy
        name: privacy_policy
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: Exclude from Search
            name: search_exclude
            widget: select
            default: "no"
            options: ["yes", "no"]

      - file: site/content/terms-and-conditions/_index.md
        label: Terms and Conditions
        name: terms_and_conditions
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Image
            name: image
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: Exclude from Search
            name: search_exclude
            widget: select
            default: "no"
            options: ["yes", "no"]
